# Generated by Django 4.0 on 2021-12-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPKTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('user_name', models.CharField(max_length=100)),
                ('isi', models.TextField()),
                ('stop_removal', models.TextField()),
            ],
        ),
    ]
