# Generated by Django 4.0 on 2021-12-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpktweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpktweet',
            name='tanggal',
            field=models.DateTimeField(),
        ),
    ]
