# Generated by Django 4.0 on 2022-03-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpktweet', '0003_alter_kpktweet_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpktweet',
            name='label',
            field=models.CharField(default='netral', max_length=10),
        ),
        migrations.AddField(
            model_name='kpktweet',
            name='polarity',
            field=models.CharField(default='[0]', max_length=5),
        ),
    ]
