# Generated by Django 4.0 on 2022-03-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpktweet', '0004_kpktweet_label_kpktweet_polarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpktweet',
            name='label',
            field=models.CharField(default='netral', max_length=10),
        ),
        migrations.AlterField(
            model_name='kpktweet',
            name='polarity',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
