# Generated by Django 4.0 on 2022-03-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpktweet', '0005_alter_kpktweet_label_alter_kpktweet_polarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPKTweetTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.TextField()),
                ('user_name', models.CharField(max_length=100)),
                ('isi', models.TextField()),
                ('stop_removal', models.TextField()),
                ('label', models.CharField(default='netral', max_length=10)),
                ('polarity', models.CharField(default='[0]', max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='kpktweet',
            name='polarity',
            field=models.CharField(default='[0]', max_length=5),
        ),
    ]
