# Generated by Django 4.0 on 2022-03-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpktweet', '0006_kpktweettemp_alter_kpktweet_polarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpktweettemp',
            name='polarity',
            field=models.CharField(default='[0]', max_length=10),
        ),
    ]
